### ISSUE TITLE
[BUG]: Setting up API Key

### ISSUE THREAD

**Issue by jjfantini** [OpenBB-finance/openbb-cookiecutter#10]
I have looked over #7, but have not been able to apply the solution to my use case.

I am building [openbb-orats](https://github.com/jjfantini/openbb-orats), and this requires an `api_key`.

I have followed along with the template tutorial, but am not having any luck in setting an `api_key`.

The package name: openbb-orats
Provider Name: orats

When I run the below code, I don't see any available credentials to set? The credentials field in `Provider()` is uncommented.
```py
obb.user.credentials

# Credentials
```

I have tried to set the key, to no avail.

```py

from openbb_orats import obb
import openbb_orats

openbb_orats.build()

obb.user.credentials.openbb_orats_api_key = "test"
obb.user.credentials.orats_api_key = "test"
```

**Comment by jjfantini** [comment]
@IgorWounds any suggestion on how to rectify would be appreciated :)

**Comment by IgorWounds** [comment]
Hi @jjfantini !

Did you follow the cookiecutter as it is written? Did you pip install again after you've changed your provider file?

As for setting the credential, it would be your provider name + the name of your key `obb.user.credentials.my_module_api_key`.

Can you please show me your `Provider` file?

**Comment by jjfantini** [comment]
Yup! I have pip installed after changing the provider file. I can show you the file, but also feel free to look at the repo, it's public :)

```
#provider.py

"""openbb_orats OpenBB Platform Provider."""

from openbb_core.provider.abstract.provider import Provider

from openbb_orats.models.tickers import OratsTickersOptionsChainsFetcher

# mypy: disable-error-code="list-item"

provider = Provider(
    name="orats",
    description="Data provider for ORATS.",
    # Only add 'credentials' if they are needed.
    # For multiple login details, list them all here.
    credentials=["api_key"],
    website="https://orats.com",
    # Here, we list out the fetchers showing what our provider can get.
    # The dictionary key is the fetcher's name, used in the `router.py`.
    fetcher_dict={
        "Tickers": OratsTickersOptionsChainsFetcher,
    },
)

```

**Comment by jjfantini** [comment]
Nope, it doesn't. Here is the error I get:

```py
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[130], [line 9](vscode-notebook-cell:?execution_count=130&line=9)
      [5](vscode-notebook-cell:?execution_count=130&line=5) import openbb_orats
      [7](vscode-notebook-cell:?execution_count=130&line=7) openbb_orats.build()
----> [9](vscode-notebook-cell:?execution_count=130&line=9) obb.user.credentials.orats_api_key = "test"

File [c:\Users\jjfan\github\openbb-orats\menv\Lib\site-packages\pydantic\main.py:792](file:///C:/Users/jjfan/github/openbb-orats/menv/Lib/site-packages/pydantic/main.py:792), in BaseModel.__setattr__(self, name, value)
    [790](file:///C:/Users/jjfan/github/openbb-orats/menv/Lib/site-packages/pydantic/main.py:790)     attr.__set__(self, value)
    [791](file:///C:/Users/jjfan/github/openbb-orats/menv/Lib/site-packages/pydantic/main.py:791) elif self.model_config.get('validate_assignment', None):
--> [792](file:///C:/Users/jjfan/github/openbb-orats/menv/Lib/site-packages/pydantic/main.py:792)     self.__pydantic_validator__.validate_assignment(self, name, value)
    [793](file:///C:/Users/jjfan/github/openbb-orats/menv/Lib/site-packages/pydantic/main.py:793) elif self.model_config.get('extra') != 'allow' and name not in self.model_fields:
    [794](file:///C:/Users/jjfan/github/openbb-orats/menv/Lib/site-packages/pydantic/main.py:794)     # TODO - matching error
    [795](file:///C:/Users/jjfan/github/openbb-orats/menv/Lib/site-packages/pydantic/main.py:795)     raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')

ValidationError: 1 validation error for Credentials
orats_api_key
  Object has no attribute 'orats_api_key' [type=no_such_attribute, input_value='test', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/no_such_attribute
```

**Comment by IgorWounds** [comment]
I don't have an issue. Is your notebook using the right environment?

![Screenshot 2024-02-16 at 14 16 13](https://github.com/OpenBB-finance/openbb-cookiecutter/assets/74266147/f298795d-1327-4480-ad0f-e1a701d0536f)

**Comment by IgorWounds** [comment]
![Uploading Screenshot 2024-02-16 at 14.22.17.jpg…]()

**Comment by jjfantini** [comment]
But it is using my micromamba environment, which is where I have this project loaded.

**Comment by jjfantini** [comment]
Hmmmm...this is odd. It seems to be working now, and I can find and set the `api_key` correctly. I'm curious as to what the issue was? 

It started working after I imported openbb_orats from the CLI, but not when I used the notebook first.

**Comment by IgorWounds** [comment]
I think that your notebook might have not restarted itself correctly after the changes.

**Comment by jjfantini** [comment]
I appreciate you spending the time to troubleshoot this! 🙏🏼
