### ISSUE TITLE
Setting api key to new Extension.

### ISSUE THREAD

**Issue by caiquecober** [OpenBB-finance/openbb-cookiecutter#7]
<img width="569" alt="image" src="https://github.com/OpenBB-finance/openbb-cookiecutter/assets/67133227/70916228-ae66-47ef-825e-c7c29ec188c4">

<img width="733" alt="image" src="https://github.com/OpenBB-finance/openbb-cookiecutter/assets/67133227/c4a335f7-3684-4b9c-97ed-61a16f032393">

<img width="742" alt="image" src="https://github.com/OpenBB-finance/openbb-cookiecutter/assets/67133227/b54cc4fd-735d-4bae-9420-435477bdcdb3">

<img width="685" alt="image" src="https://github.com/OpenBB-finance/openbb-cookiecutter/assets/67133227/552934c0-595e-4ce4-8cb4-28e354d8ed75">

This is the extension im building but the setting a new api key is falling
When i call the function directly before setting the key it dosent work as expected and raises the value error missing key.

When i try setting the api key as the openbb-cookiecutter sugestt i get a error, what am i missing here igor.

<img width="582" alt="image" src="https://github.com/OpenBB-finance/openbb-cookiecutter/assets/67133227/93fab63d-4309-4a6a-ade9-a63a1179d69c">

Thanks for the help,
Best,
Cober

**Comment by IgorWounds** [comment]
Hi @caiquecober ,

Picture 1 -> The import of the fetcher is wrong as its name is not `ExampleFetcher` anymore but is `EIATimeSeriesData`. Same now goes for the fetcher dictionary where you want to add this fetcher.

Picture 2 -> The import of the utils is wrong. It should be a relative one by adding an extra `.` in front.

This will fix your issue.

![Screenshot 2024-01-21 at 21 45 12](https://github.com/OpenBB-finance/openbb-cookiecutter/assets/74266147/0d68dcd7-b744-4985-91c8-f7cd17026b7b)

Hope this helps!
