### ISSUE TITLE
[BUG]: Clarify the `provider` object name

### ISSUE THREAD

**Issue by jjfantini** [OpenBB-finance/openbb-cookiecutter#8]
I am building an openbb extension with the openbb-cookiecutter template.

When I run:
```py
> from openbb_orats import obb
```

I get the error:
```py
module 'openbb_orats.provider' has no attribute 'provider'
```

The CONTRIBUTING GUIDELINES explain that I should put the provider in the `__init__.py` file, but the cookiecutter template adds a whole modules for this.

Should I put the provider in the `__init__.py` file or should I keep the provider module?

EXTRA INFO:
```py
[tool.poetry.plugins."openbb_provider_extension"]
openbb_orats = "openbb_orats.provider:orats_provider"
```

```py
#provider.py module

orats_provider = Provider()
```

When I run:
```py
> from openbb_orats.provider import orats_provider
```

This executes without issue. Any help would be appreciated!

**Comment by jjfantini** [comment]
I changed the `provider` name^^ in the provider module to reference the name of the provider, like `provider` modules have done in the `openbb_platform` module.

i.e
For Nasdaq:
```py
nasdaq_provider = Provider()
```
You should think about clarifying that you don't need to change the provider object and it can just be:
```
provider = Provider()
```

**Comment by IgorWounds** [comment]
Hi,

Thanks for raising this. I'd suggest following the cookiecutter template and examples as is. The cookiecutter, although it leverages the `openbb-core`, isn't an 1:1 mapping to the OpenBB Platform. In the case of the cookiecutter we want to keep it lean and to avoid issues the provider gained its own module.

To answer your question, keep it in the provider module.

As for the second part, you can name your variables in any way you prefer. The most important thing is that the entry point is correctly declared in the toml.

**Comment by jjfantini** [comment]
Thanks for the quick response :). I will keep it in the cookie-cutter template form. 

To get back to the initial issue at hand: 

I have fixed the error by leaving the object's variable name as `provider`. Even if I correctly reference the entry point in the `pyproject.toml` file, I still get the error. I think the `__init__.py` file that builds the extension app is not correctly looking for provider, it seems to only look for `provider` variable name.

Wouldn't
```py
[tool.poetry.plugins."openbb_provider_extension"]
openbb_orats = "openbb_orats.provider:orats_provider"
```
be the correct entry point to the provider module and the object variable

```py
orats_provider = Provider()
```
,as stated above?

**Comment by IgorWounds** [comment]
That should be the case and should work. Make sure to pip install again so it picks up the changes in the `pyproject.toml`. You are likely facing and environment issue.

**Comment by IgorWounds** [comment]
@jjfantini heads up that I pushed a uvicorn fix that slightly changes the import statement. Now it is `from my_ext.openbb import obb`
